### ISSUE TITLE
Weird Puppetfile.lock error

### ISSUE THREAD

**Issue by stack72** [justindowning/puppet-statsd#9]
When i switched away from the puppetlabs operations version of statsd to this module, i tried to use the git commit for master as follows:

```
mod 'jdowning/statsd',
  :git => 'https://github.com/justindowning/puppet-statsd.git',
  :ref => '4175c34f0a8900b51b30d0e4955a6b55c2e4655c'
```

It caused the following error:

```
bundle exec librarian-puppet install
Cannot bounce Puppetfile.lock!
rake aborted!
Command failed with status (1): [bundle exec librarian-puppet install...]
/Users/pstack/Documents/Projects/puppet-modules/Rakefile:25:in `block in <top (required)>'
/Users/pstack/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `eval'
/Users/pstack/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => librarian_puppet_test
(See full trace by running task with --trace)
```

When i changed my Puppetfile to be as follows:

```
mod 'jdowning/statsd', '2.0.1'
```

(and using the forge version of the module) all worked well

Very strange, so thought I'd report it.

**Comment by everestx** [comment]
I'll comment here for posterity.  I removed the above commit from PR #25 since it's essentially a can of worms.  The reason this is happening is because there are conflicting dependencies specified in `Puppetfile.lock`, `Puppetfile` and `metadata.json`.  This error doesn't happen when installing from Puppet Forge, since those releases are sanitized when packaging for the forge.

The long term fix would be one of two options:
  1. Don't specify a Puppetfile.lock or Puppetfile in the git repo (or obfuscate it from the root)
  1. Maintain version matching between metadata.json and the Puppetfile(s)

Both of these options will get more complicated, since the `vagrant/*` test files currently depend on puppet-community/nodejs `<1.0.0` and v1 had breaking changes.

**Comment by justindowning** [comment]
@everestx I like having the `Puppetfile.lock` committed so any developer can be assured of working with the same environment as any other contributor (just like with a `Gemfile.lock` in a ruby project).
